### ISSUE TITLE
Add build stages to .travis.yml

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#26694]
**Is your feature request related to a problem? Please describe.**  
The large number of build targets we use on travis, coupled with the large number of open PRs we maintain leads to very long build queue times for both pull requests and master branch builds.

**Describe the solution you'd like**  
Travis build stages https://docs.travis-ci.com/user/build-stages/ provide a mechanism for managing many-step build processes.
In particular, starting off each build with a single build step that validates astyle, json style, performs a build, and runs the test suite will cause build jobs to fail fast in case of the most common errors, leaving more build workers available for completing other steps in the queue.

**Describe alternatives you've considered**  
Reducing the number of build stages is likely a reasonable thing to do, but even with that number minimized, blocking each build on a single stage that will cancel the remaining builds if it fails will be a win.

**Additional context**
Due to what is probably a bug in travis, https://github.com/travis-ci/travis-ci/issues/8295, build stages and matrix builds seem to be incompatible.  What is likely needed is to replace the existing matrix build with a "jobs" section that fills the same purpose, but also enumerates build stages.
```
jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.3
    - stage: test
      script: bundle show
      rvm: 2.3
    - stage: test
      script: bundle show
      rvm: 2.3
    - stage: test
      script: bundle show
      rvm: 2.3
```
