### ISSUE TITLE
Uniformly use 8-bit escape code colors 

### ISSUE THREAD

**Issue by ming2k** [CleverRaven/Cataclysm-DDA#78720]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/d2cd67fc-0481-44fa-b06a-7d36176d4a6d)

As the picture, the letter color of the inventory's above tab and background blend, difficulty distinguishing correct information.

### Solution you would like.

I have checked the related docs, i found the DGRAY color don't following the [escape code colors](https://en.wikipedia.org/wiki/ANSI_escape_code#colors) 3 or 4 bit, but the background and other color following it, i hope the color can uniformly use 8 bit escape code colors to ensure consistent performance on different machines.

**Comment by ZhilkinSerg** [comment]
You need to provide more details - game version, OS, terminal software used, etc.

**Comment by ming2k** [comment]
> You need to provide more details - game version, OS, terminal software used, etc.

Hi, this is the related info:

Game Version: 0.H Stable Candidate, build 0.H
OS: Arch Linux
Terminal Emulator: Alacritty

Besides, i think the alacritty color config will be helpful like this:

```toml
[colors.primary]
background = "#ffffff"
foreground = "#383a42"

[colors.cursor]
text = "#ffffff"
cursor = "#383a42"

[colors.selection]
text = "#383a42"
background = "#e5e5e6"

[colors.normal]
black = "#383a42"
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"
blue = "#0184bc"
magenta = "#a626a4"
cyan = "#0997b3"
white = "#909090"

[colors.bright]
black = "#383a42"
red = "#ff6b66"
green = "#87c782"
yellow = "#e4b51c"
blue = "#4cb2ff"
magenta = "#b941b9"
cyan = "#1cb0cd"
white = "#595959"
```

If there is any other information you need me to provide, please let me know, thank you
